name: new contexts
on:
  push:
jobs:
  contexts:
    runs-on: ubuntu-latest
    steps:
      - name: describes github contexts
        run: |
          echo "Repository name: ${{ github.repository }}"
          echo "Branch name: ${{ github.ref_name }}"
          echo "Commit id: ${{ github.sha }}"
          echo "Runner's OS: ${{ runner.os }}"
