name: inspect the runner
on:
  push:
jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Print runner's kernel details
        run: |
          uname -a
          ls -la
      - name: Line repository contains
        run: find . -type f | wc -l
